apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: url-shortener:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"    
            - name: BASE_URL
              value: "http://127.0.0.1:5000"
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 250m
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  type: LoadBalancer
  selector:
    app: url-shortener
  ports:
    - port: 5000
      targetPort: 5000

